name: MedusaJS

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    branches: [main, master]

jobs:
  build:
    name: Build MedusaJS images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [backend, admin, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and publish Docker image for ${{matrix.server}}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_${{matrix.server}}
          tags: jmflaherty/medusajs-${{matrix.server}}:latest
          push: true
